// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Grade.proto

package com.liyulin.protobuf.proto;

public final class GradeDTO {
  private GradeDTO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GradeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Grade)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Student student = 1;</code>
     */
    java.util.List<com.liyulin.protobuf.proto.StudentDTO.Student> 
        getStudentList();
    /**
     * <code>repeated .Student student = 1;</code>
     */
    com.liyulin.protobuf.proto.StudentDTO.Student getStudent(int index);
    /**
     * <code>repeated .Student student = 1;</code>
     */
    int getStudentCount();
    /**
     * <code>repeated .Student student = 1;</code>
     */
    java.util.List<? extends com.liyulin.protobuf.proto.StudentDTO.StudentOrBuilder> 
        getStudentOrBuilderList();
    /**
     * <code>repeated .Student student = 1;</code>
     */
    com.liyulin.protobuf.proto.StudentDTO.StudentOrBuilder getStudentOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Grade}
   */
  public  static final class Grade extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Grade)
      GradeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Grade.newBuilder() to construct.
    private Grade(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Grade() {
      student_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Grade();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Grade(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                student_ = new java.util.ArrayList<com.liyulin.protobuf.proto.StudentDTO.Student>();
                mutable_bitField0_ |= 0x00000001;
              }
              student_.add(
                  input.readMessage(com.liyulin.protobuf.proto.StudentDTO.Student.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          student_ = java.util.Collections.unmodifiableList(student_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.liyulin.protobuf.proto.GradeDTO.internal_static_Grade_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.liyulin.protobuf.proto.GradeDTO.internal_static_Grade_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.liyulin.protobuf.proto.GradeDTO.Grade.class, com.liyulin.protobuf.proto.GradeDTO.Grade.Builder.class);
    }

    public static final int STUDENT_FIELD_NUMBER = 1;
    private java.util.List<com.liyulin.protobuf.proto.StudentDTO.Student> student_;
    /**
     * <code>repeated .Student student = 1;</code>
     */
    public java.util.List<com.liyulin.protobuf.proto.StudentDTO.Student> getStudentList() {
      return student_;
    }
    /**
     * <code>repeated .Student student = 1;</code>
     */
    public java.util.List<? extends com.liyulin.protobuf.proto.StudentDTO.StudentOrBuilder> 
        getStudentOrBuilderList() {
      return student_;
    }
    /**
     * <code>repeated .Student student = 1;</code>
     */
    public int getStudentCount() {
      return student_.size();
    }
    /**
     * <code>repeated .Student student = 1;</code>
     */
    public com.liyulin.protobuf.proto.StudentDTO.Student getStudent(int index) {
      return student_.get(index);
    }
    /**
     * <code>repeated .Student student = 1;</code>
     */
    public com.liyulin.protobuf.proto.StudentDTO.StudentOrBuilder getStudentOrBuilder(
        int index) {
      return student_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getStudentCount(); i++) {
        if (!getStudent(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < student_.size(); i++) {
        output.writeMessage(1, student_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < student_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, student_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.liyulin.protobuf.proto.GradeDTO.Grade)) {
        return super.equals(obj);
      }
      com.liyulin.protobuf.proto.GradeDTO.Grade other = (com.liyulin.protobuf.proto.GradeDTO.Grade) obj;

      if (!getStudentList()
          .equals(other.getStudentList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getStudentCount() > 0) {
        hash = (37 * hash) + STUDENT_FIELD_NUMBER;
        hash = (53 * hash) + getStudentList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.liyulin.protobuf.proto.GradeDTO.Grade parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.liyulin.protobuf.proto.GradeDTO.Grade parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.liyulin.protobuf.proto.GradeDTO.Grade parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.liyulin.protobuf.proto.GradeDTO.Grade parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.liyulin.protobuf.proto.GradeDTO.Grade parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.liyulin.protobuf.proto.GradeDTO.Grade parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.liyulin.protobuf.proto.GradeDTO.Grade parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.liyulin.protobuf.proto.GradeDTO.Grade parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.liyulin.protobuf.proto.GradeDTO.Grade parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.liyulin.protobuf.proto.GradeDTO.Grade parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.liyulin.protobuf.proto.GradeDTO.Grade parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.liyulin.protobuf.proto.GradeDTO.Grade parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.liyulin.protobuf.proto.GradeDTO.Grade prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Grade}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Grade)
        com.liyulin.protobuf.proto.GradeDTO.GradeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.liyulin.protobuf.proto.GradeDTO.internal_static_Grade_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.liyulin.protobuf.proto.GradeDTO.internal_static_Grade_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.liyulin.protobuf.proto.GradeDTO.Grade.class, com.liyulin.protobuf.proto.GradeDTO.Grade.Builder.class);
      }

      // Construct using com.liyulin.protobuf.proto.GradeDTO.Grade.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getStudentFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (studentBuilder_ == null) {
          student_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          studentBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.liyulin.protobuf.proto.GradeDTO.internal_static_Grade_descriptor;
      }

      @java.lang.Override
      public com.liyulin.protobuf.proto.GradeDTO.Grade getDefaultInstanceForType() {
        return com.liyulin.protobuf.proto.GradeDTO.Grade.getDefaultInstance();
      }

      @java.lang.Override
      public com.liyulin.protobuf.proto.GradeDTO.Grade build() {
        com.liyulin.protobuf.proto.GradeDTO.Grade result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.liyulin.protobuf.proto.GradeDTO.Grade buildPartial() {
        com.liyulin.protobuf.proto.GradeDTO.Grade result = new com.liyulin.protobuf.proto.GradeDTO.Grade(this);
        int from_bitField0_ = bitField0_;
        if (studentBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            student_ = java.util.Collections.unmodifiableList(student_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.student_ = student_;
        } else {
          result.student_ = studentBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.liyulin.protobuf.proto.GradeDTO.Grade) {
          return mergeFrom((com.liyulin.protobuf.proto.GradeDTO.Grade)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.liyulin.protobuf.proto.GradeDTO.Grade other) {
        if (other == com.liyulin.protobuf.proto.GradeDTO.Grade.getDefaultInstance()) return this;
        if (studentBuilder_ == null) {
          if (!other.student_.isEmpty()) {
            if (student_.isEmpty()) {
              student_ = other.student_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureStudentIsMutable();
              student_.addAll(other.student_);
            }
            onChanged();
          }
        } else {
          if (!other.student_.isEmpty()) {
            if (studentBuilder_.isEmpty()) {
              studentBuilder_.dispose();
              studentBuilder_ = null;
              student_ = other.student_;
              bitField0_ = (bitField0_ & ~0x00000001);
              studentBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getStudentFieldBuilder() : null;
            } else {
              studentBuilder_.addAllMessages(other.student_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        for (int i = 0; i < getStudentCount(); i++) {
          if (!getStudent(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.liyulin.protobuf.proto.GradeDTO.Grade parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.liyulin.protobuf.proto.GradeDTO.Grade) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.liyulin.protobuf.proto.StudentDTO.Student> student_ =
        java.util.Collections.emptyList();
      private void ensureStudentIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          student_ = new java.util.ArrayList<com.liyulin.protobuf.proto.StudentDTO.Student>(student_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.liyulin.protobuf.proto.StudentDTO.Student, com.liyulin.protobuf.proto.StudentDTO.Student.Builder, com.liyulin.protobuf.proto.StudentDTO.StudentOrBuilder> studentBuilder_;

      /**
       * <code>repeated .Student student = 1;</code>
       */
      public java.util.List<com.liyulin.protobuf.proto.StudentDTO.Student> getStudentList() {
        if (studentBuilder_ == null) {
          return java.util.Collections.unmodifiableList(student_);
        } else {
          return studentBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Student student = 1;</code>
       */
      public int getStudentCount() {
        if (studentBuilder_ == null) {
          return student_.size();
        } else {
          return studentBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Student student = 1;</code>
       */
      public com.liyulin.protobuf.proto.StudentDTO.Student getStudent(int index) {
        if (studentBuilder_ == null) {
          return student_.get(index);
        } else {
          return studentBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Student student = 1;</code>
       */
      public Builder setStudent(
          int index, com.liyulin.protobuf.proto.StudentDTO.Student value) {
        if (studentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentIsMutable();
          student_.set(index, value);
          onChanged();
        } else {
          studentBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Student student = 1;</code>
       */
      public Builder setStudent(
          int index, com.liyulin.protobuf.proto.StudentDTO.Student.Builder builderForValue) {
        if (studentBuilder_ == null) {
          ensureStudentIsMutable();
          student_.set(index, builderForValue.build());
          onChanged();
        } else {
          studentBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Student student = 1;</code>
       */
      public Builder addStudent(com.liyulin.protobuf.proto.StudentDTO.Student value) {
        if (studentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentIsMutable();
          student_.add(value);
          onChanged();
        } else {
          studentBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Student student = 1;</code>
       */
      public Builder addStudent(
          int index, com.liyulin.protobuf.proto.StudentDTO.Student value) {
        if (studentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentIsMutable();
          student_.add(index, value);
          onChanged();
        } else {
          studentBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Student student = 1;</code>
       */
      public Builder addStudent(
          com.liyulin.protobuf.proto.StudentDTO.Student.Builder builderForValue) {
        if (studentBuilder_ == null) {
          ensureStudentIsMutable();
          student_.add(builderForValue.build());
          onChanged();
        } else {
          studentBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Student student = 1;</code>
       */
      public Builder addStudent(
          int index, com.liyulin.protobuf.proto.StudentDTO.Student.Builder builderForValue) {
        if (studentBuilder_ == null) {
          ensureStudentIsMutable();
          student_.add(index, builderForValue.build());
          onChanged();
        } else {
          studentBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Student student = 1;</code>
       */
      public Builder addAllStudent(
          java.lang.Iterable<? extends com.liyulin.protobuf.proto.StudentDTO.Student> values) {
        if (studentBuilder_ == null) {
          ensureStudentIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, student_);
          onChanged();
        } else {
          studentBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Student student = 1;</code>
       */
      public Builder clearStudent() {
        if (studentBuilder_ == null) {
          student_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          studentBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Student student = 1;</code>
       */
      public Builder removeStudent(int index) {
        if (studentBuilder_ == null) {
          ensureStudentIsMutable();
          student_.remove(index);
          onChanged();
        } else {
          studentBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Student student = 1;</code>
       */
      public com.liyulin.protobuf.proto.StudentDTO.Student.Builder getStudentBuilder(
          int index) {
        return getStudentFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Student student = 1;</code>
       */
      public com.liyulin.protobuf.proto.StudentDTO.StudentOrBuilder getStudentOrBuilder(
          int index) {
        if (studentBuilder_ == null) {
          return student_.get(index);  } else {
          return studentBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Student student = 1;</code>
       */
      public java.util.List<? extends com.liyulin.protobuf.proto.StudentDTO.StudentOrBuilder> 
           getStudentOrBuilderList() {
        if (studentBuilder_ != null) {
          return studentBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(student_);
        }
      }
      /**
       * <code>repeated .Student student = 1;</code>
       */
      public com.liyulin.protobuf.proto.StudentDTO.Student.Builder addStudentBuilder() {
        return getStudentFieldBuilder().addBuilder(
            com.liyulin.protobuf.proto.StudentDTO.Student.getDefaultInstance());
      }
      /**
       * <code>repeated .Student student = 1;</code>
       */
      public com.liyulin.protobuf.proto.StudentDTO.Student.Builder addStudentBuilder(
          int index) {
        return getStudentFieldBuilder().addBuilder(
            index, com.liyulin.protobuf.proto.StudentDTO.Student.getDefaultInstance());
      }
      /**
       * <code>repeated .Student student = 1;</code>
       */
      public java.util.List<com.liyulin.protobuf.proto.StudentDTO.Student.Builder> 
           getStudentBuilderList() {
        return getStudentFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.liyulin.protobuf.proto.StudentDTO.Student, com.liyulin.protobuf.proto.StudentDTO.Student.Builder, com.liyulin.protobuf.proto.StudentDTO.StudentOrBuilder> 
          getStudentFieldBuilder() {
        if (studentBuilder_ == null) {
          studentBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.liyulin.protobuf.proto.StudentDTO.Student, com.liyulin.protobuf.proto.StudentDTO.Student.Builder, com.liyulin.protobuf.proto.StudentDTO.StudentOrBuilder>(
                  student_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          student_ = null;
        }
        return studentBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Grade)
    }

    // @@protoc_insertion_point(class_scope:Grade)
    private static final com.liyulin.protobuf.proto.GradeDTO.Grade DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.liyulin.protobuf.proto.GradeDTO.Grade();
    }

    public static com.liyulin.protobuf.proto.GradeDTO.Grade getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Grade>
        PARSER = new com.google.protobuf.AbstractParser<Grade>() {
      @java.lang.Override
      public Grade parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Grade(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Grade> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Grade> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.liyulin.protobuf.proto.GradeDTO.Grade getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Grade_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Grade_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Grade.proto\032\rStudent.proto\"\"\n\005Grade\022\031\n" +
      "\007student\030\001 \003(\0132\010.StudentB&\n\032com.liyulin." +
      "protobuf.protoB\010GradeDTO"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.liyulin.protobuf.proto.StudentDTO.getDescriptor(),
        });
    internal_static_Grade_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Grade_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Grade_descriptor,
        new java.lang.String[] { "Student", });
    com.liyulin.protobuf.proto.StudentDTO.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
