CREATE TABLE `t_user` (
  `f_id` bigint(20) NOT NULL COMMENT '用户编号',
  `f_mobile` varchar(11) DEFAULT NULL COMMENT '手机号',
  `f_nick_name` varchar(45) DEFAULT NULL COMMENT '昵称',
  `f_real_name` varchar(45) DEFAULT NULL COMMENT '真实姓名',
  `f_sex` varchar(4) DEFAULT NULL COMMENT '性别=={"M":"男","F":"女","X":"未知"}',
  `f_birthday` date DEFAULT NULL COMMENT '出生年月',
  `f_imgProfile` varchar(255) DEFAULT NULL COMMENT '图像',
  `f_user_state` int(2) NOT NULL COMMENT '用户状态=={"0":"启用","1":"禁用"}',
  `f_passwd_status` int(2) DEFAULT NULL COMMENT '密码状态=={"1":"未设置","2":"已设置"''}',
  `f_channel` int(2) NOT NULL COMMENT '所在平台=={"1":"微信","2":"web后台"}',
  `f_openId` varchar(35) DEFAULT NULL COMMENT '微信openId',
  `f_user_type` int(2) NOT NULL COMMENT '用户类别=={"1":"普通用户","2":''代理人","99":"管理员"}',
  `f_last_login_time` datetime DEFAULT NULL COMMENT '最近成功登录时间',
  `f_sys_add_time` datetime DEFAULT NULL COMMENT '新增时间',
  `f_sys_upd_time` datetime DEFAULT NULL COMMENT '更新时间',
  `f_sys_del_time` datetime DEFAULT NULL COMMENT '删除时间',
  `f_sys_add_user` bigint(20) DEFAULT NULL COMMENT '新增者',
  `f_sys_upd_user` bigint(20) DEFAULT NULL COMMENT '修改者',
  `f_sys_del_user` bigint(20) DEFAULT NULL COMMENT '删除者',
  `f_sys_del_state` int(1) NOT NULL COMMENT '记录状态=={"0":"正常","1":"已删除"}',
  PRIMARY KEY (`f_id`),
  UNIQUE KEY `f_mobile` (`f_mobile`),
  UNIQUE KEY `f_openId` (`f_openId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=COMPACT COMMENT='用户表';