
package com.liyulin.jws.webservice.client.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JwsServiceImpl", targetNamespace = "http://service.server.webservice.jws.liyulin.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JwsServiceImpl {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://service.server.webservice.jws.liyulin.com/", className = "com.liyulin.jws.webservice.client.service.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://service.server.webservice.jws.liyulin.com/", className = "com.liyulin.jws.webservice.client.service.AddResponse")
    @Action(input = "http://service.server.webservice.jws.liyulin.com/JwsServiceImpl/addRequest", output = "http://service.server.webservice.jws.liyulin.com/JwsServiceImpl/addResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "minus", targetNamespace = "http://service.server.webservice.jws.liyulin.com/", className = "com.liyulin.jws.webservice.client.service.Minus")
    @ResponseWrapper(localName = "minusResponse", targetNamespace = "http://service.server.webservice.jws.liyulin.com/", className = "com.liyulin.jws.webservice.client.service.MinusResponse")
    @Action(input = "http://service.server.webservice.jws.liyulin.com/JwsServiceImpl/minusRequest", output = "http://service.server.webservice.jws.liyulin.com/JwsServiceImpl/minusResponse")
    public int minus(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
