
package com.liyulin.jws.webservice.client.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "JwsServiceImplService", targetNamespace = "http://service.server.webservice.jws.liyulin.com/", wsdlLocation = "http://localhost:7777/ns?wsdl")
public class JwsServiceImplService
    extends Service
{

    private final static URL JWSSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException JWSSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName JWSSERVICEIMPLSERVICE_QNAME = new QName("http://service.server.webservice.jws.liyulin.com/", "JwsServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7777/ns?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JWSSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        JWSSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public JwsServiceImplService() {
        super(__getWsdlLocation(), JWSSERVICEIMPLSERVICE_QNAME);
    }

    public JwsServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), JWSSERVICEIMPLSERVICE_QNAME, features);
    }

    public JwsServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, JWSSERVICEIMPLSERVICE_QNAME);
    }

    public JwsServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JWSSERVICEIMPLSERVICE_QNAME, features);
    }

    public JwsServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JwsServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns JwsServiceImpl
     */
    @WebEndpoint(name = "JwsServiceImplPort")
    public JwsServiceImpl getJwsServiceImplPort() {
        return super.getPort(new QName("http://service.server.webservice.jws.liyulin.com/", "JwsServiceImplPort"), JwsServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JwsServiceImpl
     */
    @WebEndpoint(name = "JwsServiceImplPort")
    public JwsServiceImpl getJwsServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.server.webservice.jws.liyulin.com/", "JwsServiceImplPort"), JwsServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JWSSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw JWSSERVICEIMPLSERVICE_EXCEPTION;
        }
        return JWSSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
