
package com.liyulin.webservice.client.user;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IUserService", targetNamespace = "http://service.webservice.liyulin.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IUserService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.liyulin.webservice.client.user.UserRespBody
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://service.webservice.liyulin.com/", className = "com.liyulin.webservice.client.user.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://service.webservice.liyulin.com/", className = "com.liyulin.webservice.client.user.GetUserResponse")
    public UserRespBody getUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserName", targetNamespace = "http://service.webservice.liyulin.com/", className = "com.liyulin.webservice.client.user.GetUserName")
    @ResponseWrapper(localName = "getUserNameResponse", targetNamespace = "http://service.webservice.liyulin.com/", className = "com.liyulin.webservice.client.user.GetUserNameResponse")
    public String getUserName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
