
package com.liyulin.webservice.client.shopping;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IShoppingService", targetNamespace = "http://service.webservice.liyulin.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IShoppingService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.liyulin.webservice.client.shopping.OrderRespBody
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buy", targetNamespace = "http://service.webservice.liyulin.com/", className = "com.liyulin.webservice.client.shopping.Buy")
    @ResponseWrapper(localName = "buyResponse", targetNamespace = "http://service.webservice.liyulin.com/", className = "com.liyulin.webservice.client.shopping.BuyResponse")
    public OrderRespBody buy(
        @WebParam(name = "arg0", targetNamespace = "")
        ProductReqBody arg0);

}
