
package com.liyulin.webservice.client.shopping;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ShoppingService", targetNamespace = "http://service.webservice.liyulin.com/", wsdlLocation = "http://127.0.0.1/shopping?wsdl")
public class ShoppingService
    extends Service
{

    private final static URL SHOPPINGSERVICE_WSDL_LOCATION;
    private final static WebServiceException SHOPPINGSERVICE_EXCEPTION;
    private final static QName SHOPPINGSERVICE_QNAME = new QName("http://service.webservice.liyulin.com/", "ShoppingService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1/shopping?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SHOPPINGSERVICE_WSDL_LOCATION = url;
        SHOPPINGSERVICE_EXCEPTION = e;
    }

    public ShoppingService() {
        super(__getWsdlLocation(), SHOPPINGSERVICE_QNAME);
    }

    public ShoppingService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SHOPPINGSERVICE_QNAME, features);
    }

    public ShoppingService(URL wsdlLocation) {
        super(wsdlLocation, SHOPPINGSERVICE_QNAME);
    }

    public ShoppingService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SHOPPINGSERVICE_QNAME, features);
    }

    public ShoppingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShoppingService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IShoppingService
     */
    @WebEndpoint(name = "ShoppingServiceImplPort")
    public IShoppingService getShoppingServiceImplPort() {
        return super.getPort(new QName("http://service.webservice.liyulin.com/", "ShoppingServiceImplPort"), IShoppingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IShoppingService
     */
    @WebEndpoint(name = "ShoppingServiceImplPort")
    public IShoppingService getShoppingServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.webservice.liyulin.com/", "ShoppingServiceImplPort"), IShoppingService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SHOPPINGSERVICE_EXCEPTION!= null) {
            throw SHOPPINGSERVICE_EXCEPTION;
        }
        return SHOPPINGSERVICE_WSDL_LOCATION;
    }

}
